# Generated by Django 4.0.8 on 2022-12-24 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='GDP_nominal',
            new_name='gdp_nominal',
        ),
    ]
